# Generated by Django 4.2 on 2025-04-27 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='established_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
