# Generated by Django 4.2 on 2025-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_alter_department_established_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('about_us', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('infrastructure_details', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Institutional Information',
            },
        ),
    ]
