# Generated by Django 4.2 on 2025-04-28 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_app', '0005_alter_event_options_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posted_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlacementDrive',
        ),
    ]
