# Generated by Django 4.2 on 2025-04-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_app', '0006_event_posted_by_delete_placementdrive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='posted_by',
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('drive_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('salary_package', models.CharField(max_length=100)),
                ('eligibility_criteria', models.TextField()),
                ('brochure', models.FileField(blank=True, null=True, upload_to='placements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-drive_date'],
            },
        ),
    ]
